### ISSUE TITLE
Баг. Происходит смена ориентации горизонтальная/вертикальная и наоборот в мобильной версии

### ISSUE THREAD

**Issue by KalinichenkoMaria** [Barresi/sakura-front#115]
[

https://github.com/Barresi/sakura-front/assets/140902759/62121ce8-5b99-488b-b257-7a4ddf3dfb76

](url)

**Comment by Barresi** [comment]
Запретить смену ориентации невозможно, док-ва [клик](https://ru.stackoverflow.com/questions/14888/%D0%9A%D0%B0%D0%BA-%D0%B7%D0%B0%D0%BF%D1%80%D0%B5%D1%82%D0%B8%D1%82%D1%8C-%D0%BF%D0%BE%D0%B2%D0%BE%D1%80%D0%BE%D1%82-%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0)
