### ISSUE TITLE
Баг. #430 В хедере интервалы между блоками не соответствуют макетам

### ISSUE THREAD

**Issue by BorisSukhanov** [Barresi/sakura-front#136]
Окружение: macOS Sonoma v.14.3.1 (23D60), Браузер Safari v.17.3.1 (19617.2.4.11.12), Разрешение 1440х900

<img width="1437" alt="Не выдержаны интервала" src="https://github.com/Barresi/sakura-front/assets/126326969/d4ef9ab8-6739-444a-ad42-edfbaaffe263">

**Comment by Barresi** [comment]
Почему интервалы не соответствуют макетам, вроде и там и там по 30 пикселей?
