### ISSUE TITLE
Баг в верстке шапки на мобилках. 

### ISSUE THREAD

**Issue by Barresi** [Barresi/sakura-front#42]
![image](https://github.com/Barresi/sakura-front/assets/111750711/3cc1fdc2-c9ec-412e-ac84-b637fc92acb8)

Скорей всего когда ты добавил справа отступ для скролла, шапка сдвинулась на несколько пикселей.

В `MobileNav` тоже самое 
![image](https://github.com/Barresi/sakura-front/assets/111750711/03a1d2a4-35ea-490e-8f8b-f52de249b218)

**Comment by Dunissimo** [comment]
а нет, на странице регистрации нужен скролл

**Comment by Dunissimo** [comment]
просто при экране меньше 1024px убрал место под скролл. Да, будет скакать вёрстка, но всё же

**Comment by Dunissimo** [comment]
я только что понял, пока пытался это исправить. На мобильных устройствах скролл не занимает место. Чтобы это увидеть, достаточно поставить тип устройства в mobile: 
![image](https://github.com/Barresi/sakura-front/assets/75184124/3821cf47-9c83-4c04-a15f-180b1d90cdfc)

Столько времени на это убил просто так, наверное. В общем, жду твой ответ
