### ISSUE TITLE
Баг в блоке выбора таба в друзьях.

### ISSUE THREAD

**Issue by Barresi** [Barresi/sakura-front#47]
Тут все еще остался небольшой отступ снизу 
![image](https://github.com/Barresi/sakura-front/assets/111750711/9ec8945b-4bb3-4a44-9035-ebc3f0d07b5c)

**Comment by Dunissimo** [comment]
нашел класс h-fit, который делает высоту по контенту. Теперь всё чётко

**Comment by Barresi** [comment]
Все четко, закрываем

**Comment by Barresi** [comment]
Все четко, закрываем
