### ISSUE TITLE
Баг undefined undefined в тоасте.

### ISSUE THREAD

**Issue by Barresi** [Barresi/sakura-front#49]
Сейчас не могу поймать этот баг, но ты сам помнишь что иногда вместо имя юзера в тоасте был undefined undefined

**Comment by Dunissimo** [comment]
пока исправлял другое, ни разу не видел. Может быть баг обиделся и ушел :)

**Comment by Barresi** [comment]
Пока не убираем эту issue, может он все-таки есть.
