### ISSUE TITLE
Баг с адаптивом тоаста

### ISSUE THREAD

**Issue by Barresi** [Barresi/sakura-front#54]
При расширении меньше 1020рх тоаст отображается криво
![image](https://github.com/Barresi/sakura-front/assets/111750711/37a87167-4c19-4035-9ba3-0d3ddf92375d)

**Comment by Barresi** [comment]
@Dunissimo Пофиксил, чекай

**Comment by Dunissimo** [comment]
убрал перекрытие toast мобильной навигацией. Использовал неизменяемое значение пикселей, так как высота устройства не меняется динамически

**Comment by Barresi** [comment]
> убрал перекрытие toast мобильной навигацией. Использовал неизменяемое значение пикселей, так как высота устройства не меняется динамически, как ширина частенько. В общем всё работает, вроде

Тут не понял, я же вроде это пофиксил, что ты сделал?

**Comment by Barresi** [comment]
@Dunissimo

**Comment by Dunissimo** [comment]
сорян, какую-то хрень тогда сделал, либо баг какой словил
