### ISSUE TITLE
Баг на мобилках

### ISSUE THREAD

**Issue by Dunissimo** [Barresi/sakura-front#55]
Нижнее меню перекрывало вёрстку. Добавить padding родителю пробовал, но на каждой странице нужны разные значения. Поэтому добавил его каждой странице по отдельности. Проверь ещё потом

**Comment by Barresi** [comment]
Добавляй пожалуйста к таким багам скрины этого бага, без них сложно что-то понять

**Comment by Dunissimo** [comment]
![image](https://github.com/Barresi/sakura-front/assets/75184124/106d15a7-7a52-4bf6-ba01-53409d0b41a5)

**Comment by Barresi** [comment]
> отступ бы не помешал, я думаю

Так и было задумано.
