### ISSUE TITLE
Баг со стилем background всего приложения.

### ISSUE THREAD

**Issue by Barresi** [Barresi/sakura-front#56]
Если открыть фронт на мобилке и попробовать пролистать за пределы блока app, то увидим что бэкграунд прописан не на тэг Боди, а на внутренний тэг div. 
Скорей всего это компонент app![image](https://github.com/Barresi/sakura-front/assets/111750711/72dff926-4d56-48f4-8664-412c3f364bf1)

**Comment by Dunissimo** [comment]
в стилях цвет задаётся body, может это особенность браузера, это же яндекс браузер? Потом скачаю и чекну

**Comment by Dunissimo** [comment]
чекнул два браузера от яндекса, всё ок

**Comment by Barresi** [comment]
Это особенность конкретно яндекс браузера, это никак не пофиксить
