### ISSUE TITLE
Баг в тоасте, нет текста

### ISSUE THREAD

**Issue by Barresi** [Barresi/sakura-front#57]
![image](https://github.com/Barresi/sakura-front/assets/111750711/84dbe643-52a0-4793-962d-9fdd812ea3d8)

Нет текста в тоасте при любом ивенте сокета

**Comment by Barresi** [comment]
Это пофиксил. Но нашел ту же проблему в списке уведомлений
![image](https://github.com/Barresi/sakura-front/assets/111750711/5a87b6ba-9874-4376-a40b-c324e7e32de3)

**Comment by Barresi** [comment]
Это тоже пофиксил, можешь проверять

**Comment by Dunissimo** [comment]
проверил - всё было ок
