### ISSUE TITLE
Подпись под паролем вводит в заблуждение

### ISSUE THREAD

**Issue by Dunissimo** [Barresi/sakura-front#60]
![photo_2024-01-08_22-26-31](https://github.com/Barresi/sakura-front/assets/75184124/c2ec5a12-df05-4663-aa50-236921a1bbec)

Поменять на "спец символ"

**Comment by Barresi** [comment]
Хмм, тире это не символ? А к спец символам не относится тире?

**Comment by Dunissimo** [comment]
на странице регистрации в инпуте такая регулярка, её тоже поменять нужно, похоже

**Comment by Barresi** [comment]
Да, попробуй разобраться с регуляркой и добавить туда недостающие символы

**Comment by Dunissimo** [comment]
её также нужно будет поменять и на бэке

**Comment by Dunissimo** [comment]
`/^(?=.*[0-9])(?=.*[-!@#$%^&*(),.?":{}|<>])(?=.*[а-яА-Яa-zA-Z]).{8,}$/gm`
