### ISSUE TITLE
Баг. Полоса прокрутки серого цвета в мобильной версии

### ISSUE THREAD

**Issue by KalinichenkoMaria** [Barresi/sakura-front#82]
https://github.com/Barresi/sakura-front/assets/140902759/dfec1f80-56a0-4428-98fd-6f2df8a8ac8f

На iPhone 12 Pro Max полоса прокрутки тоже серого цвета

**Comment by Barresi** [comment]
Некоторые мобильные браузеры, такие как Safari (iOS) или Chrome (Android), ограничивают кастомизацию стилей полосы прокрутки. Поэтому это нельзя пофиксить
